//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kendo.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kendo.Mvc.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Background Color 的本地化字符串。
        /// </summary>
        public static string Editor_BackColor {
            get {
                return ResourceManager.GetString("Editor_BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bold 的本地化字符串。
        /// </summary>
        public static string Editor_Bold {
            get {
                return ResourceManager.GetString("Editor_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert hyperlink 的本地化字符串。
        /// </summary>
        public static string Editor_CreateLink {
            get {
                return ResourceManager.GetString("Editor_CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete &quot;{0}&quot;? 的本地化字符串。
        /// </summary>
        public static string Editor_DeleteFile {
            get {
                return ResourceManager.GetString("Editor_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 or 的本地化字符串。
        /// </summary>
        public static string Editor_DialogButtonSeparator {
            get {
                return ResourceManager.GetString("Editor_DialogButtonSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Editor_DialogCancel {
            get {
                return ResourceManager.GetString("Editor_DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        public static string Editor_DialogInsert {
            get {
                return ResourceManager.GetString("Editor_DialogInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A directory with this name was not found. 的本地化字符串。
        /// </summary>
        public static string Editor_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Editor_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 drop files here to upload 的本地化字符串。
        /// </summary>
        public static string Editor_DropFilesHere {
            get {
                return ResourceManager.GetString("Editor_DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty Folder 的本地化字符串。
        /// </summary>
        public static string Editor_EmptyFolder {
            get {
                return ResourceManager.GetString("Editor_EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select font family 的本地化字符串。
        /// </summary>
        public static string Editor_FontName {
            get {
                return ResourceManager.GetString("Editor_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (inherited font) 的本地化字符串。
        /// </summary>
        public static string Editor_FontNameInherit {
            get {
                return ResourceManager.GetString("Editor_FontNameInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select font size 的本地化字符串。
        /// </summary>
        public static string Editor_FontSize {
            get {
                return ResourceManager.GetString("Editor_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (inherited size) 的本地化字符串。
        /// </summary>
        public static string Editor_FontSizeInherit {
            get {
                return ResourceManager.GetString("Editor_FontSizeInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        public static string Editor_ForeColor {
            get {
                return ResourceManager.GetString("Editor_ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        public static string Editor_FormatBlock {
            get {
                return ResourceManager.GetString("Editor_FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alternate text 的本地化字符串。
        /// </summary>
        public static string Editor_ImageAltText {
            get {
                return ResourceManager.GetString("Editor_ImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web address 的本地化字符串。
        /// </summary>
        public static string Editor_ImageWebAddress {
            get {
                return ResourceManager.GetString("Editor_ImageWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indent 的本地化字符串。
        /// </summary>
        public static string Editor_Indent {
            get {
                return ResourceManager.GetString("Editor_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert HTML 的本地化字符串。
        /// </summary>
        public static string Editor_InsertHtml {
            get {
                return ResourceManager.GetString("Editor_InsertHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert image 的本地化字符串。
        /// </summary>
        public static string Editor_InsertImage {
            get {
                return ResourceManager.GetString("Editor_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert ordered list 的本地化字符串。
        /// </summary>
        public static string Editor_InsertOrderedList {
            get {
                return ResourceManager.GetString("Editor_InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert unordered list 的本地化字符串。
        /// </summary>
        public static string Editor_InsertUnorderedList {
            get {
                return ResourceManager.GetString("Editor_InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected file &quot;{0}&quot; is not valid. Supported file types are {1}. 的本地化字符串。
        /// </summary>
        public static string Editor_InvalidFileType {
            get {
                return ResourceManager.GetString("Editor_InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italic 的本地化字符串。
        /// </summary>
        public static string Editor_Italic {
            get {
                return ResourceManager.GetString("Editor_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center text 的本地化字符串。
        /// </summary>
        public static string Editor_JustifyCenter {
            get {
                return ResourceManager.GetString("Editor_JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Justify 的本地化字符串。
        /// </summary>
        public static string Editor_JustifyFull {
            get {
                return ResourceManager.GetString("Editor_JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align text left 的本地化字符串。
        /// </summary>
        public static string Editor_JustifyLeft {
            get {
                return ResourceManager.GetString("Editor_JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align text right 的本地化字符串。
        /// </summary>
        public static string Editor_JustifyRight {
            get {
                return ResourceManager.GetString("Editor_JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open link in new window 的本地化字符串。
        /// </summary>
        public static string Editor_LinkOpenInNewWindow {
            get {
                return ResourceManager.GetString("Editor_LinkOpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        public static string Editor_LinkText {
            get {
                return ResourceManager.GetString("Editor_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToolTip 的本地化字符串。
        /// </summary>
        public static string Editor_LinkToolTip {
            get {
                return ResourceManager.GetString("Editor_LinkToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web address 的本地化字符串。
        /// </summary>
        public static string Editor_LinkWebAddress {
            get {
                return ResourceManager.GetString("Editor_LinkWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrange by: 的本地化字符串。
        /// </summary>
        public static string Editor_OrderBy {
            get {
                return ResourceManager.GetString("Editor_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Editor_OrderByName {
            get {
                return ResourceManager.GetString("Editor_OrderByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Editor_OrderBySize {
            get {
                return ResourceManager.GetString("Editor_OrderBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outdent 的本地化字符串。
        /// </summary>
        public static string Editor_Outdent {
            get {
                return ResourceManager.GetString("Editor_Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;A file with name &quot;{0}&quot; already exists in the current directory. Do you want to overwrite it? 的本地化字符串。
        /// </summary>
        public static string Editor_OverwriteFile {
            get {
                return ResourceManager.GetString("Editor_OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Editor_Search {
            get {
                return ResourceManager.GetString("Editor_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strikethrough 的本地化字符串。
        /// </summary>
        public static string Editor_Strikethrough {
            get {
                return ResourceManager.GetString("Editor_Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Styles 的本地化字符串。
        /// </summary>
        public static string Editor_Styles {
            get {
                return ResourceManager.GetString("Editor_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscript 的本地化字符串。
        /// </summary>
        public static string Editor_Subscript {
            get {
                return ResourceManager.GetString("Editor_Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Superscript 的本地化字符串。
        /// </summary>
        public static string Editor_Superscript {
            get {
                return ResourceManager.GetString("Editor_Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underline 的本地化字符串。
        /// </summary>
        public static string Editor_Underline {
            get {
                return ResourceManager.GetString("Editor_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove hyperlink 的本地化字符串。
        /// </summary>
        public static string Editor_Unlink {
            get {
                return ResourceManager.GetString("Editor_Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        public static string Editor_UploadFile {
            get {
                return ResourceManager.GetString("Editor_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        public static string Filter_And {
            get {
                return ResourceManager.GetString("Filter_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Filter_Clear {
            get {
                return ResourceManager.GetString("Filter_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        public static string Filter_DateIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is after 的本地化字符串。
        /// </summary>
        public static string Filter_DateIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is after or equal to 的本地化字符串。
        /// </summary>
        public static string Filter_DateIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is before 的本地化字符串。
        /// </summary>
        public static string Filter_DateIsLessThan {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is before or equal to 的本地化字符串。
        /// </summary>
        public static string Filter_DateIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        public static string Filter_DateIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        public static string Filter_EnumIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        public static string Filter_EnumIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        public static string Filter_Filter {
            get {
                return ResourceManager.GetString("Filter_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show items with value that: 的本地化字符串。
        /// </summary>
        public static string Filter_Info {
            get {
                return ResourceManager.GetString("Filter_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is false 的本地化字符串。
        /// </summary>
        public static string Filter_IsFalse {
            get {
                return ResourceManager.GetString("Filter_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is true 的本地化字符串。
        /// </summary>
        public static string Filter_IsTrue {
            get {
                return ResourceManager.GetString("Filter_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        public static string Filter_NumberIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is greater than 的本地化字符串。
        /// </summary>
        public static string Filter_NumberIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is greater than or equal to 的本地化字符串。
        /// </summary>
        public static string Filter_NumberIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is less than 的本地化字符串。
        /// </summary>
        public static string Filter_NumberIsLessThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is less than or equal to 的本地化字符串。
        /// </summary>
        public static string Filter_NumberIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        public static string Filter_NumberIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or 的本地化字符串。
        /// </summary>
        public static string Filter_Or {
            get {
                return ResourceManager.GetString("Filter_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -Select value- 的本地化字符串。
        /// </summary>
        public static string Filter_SelectValue {
            get {
                return ResourceManager.GetString("Filter_SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains 的本地化字符串。
        /// </summary>
        public static string Filter_StringContains {
            get {
                return ResourceManager.GetString("Filter_StringContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Does not contain 的本地化字符串。
        /// </summary>
        public static string Filter_StringDoesNotContain {
            get {
                return ResourceManager.GetString("Filter_StringDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ends with 的本地化字符串。
        /// </summary>
        public static string Filter_StringEndsWith {
            get {
                return ResourceManager.GetString("Filter_StringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        public static string Filter_StringIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        public static string Filter_StringIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starts with 的本地化字符串。
        /// </summary>
        public static string Filter_StringStartsWith {
            get {
                return ResourceManager.GetString("Filter_StringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Grid_Cancel {
            get {
                return ResourceManager.GetString("Grid_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel changes 的本地化字符串。
        /// </summary>
        public static string Grid_CancelChanges {
            get {
                return ResourceManager.GetString("Grid_CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Columns 的本地化字符串。
        /// </summary>
        public static string Grid_Columns {
            get {
                return ResourceManager.GetString("Grid_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this item? 的本地化字符串。
        /// </summary>
        public static string Grid_Confirmation {
            get {
                return ResourceManager.GetString("Grid_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add new item 的本地化字符串。
        /// </summary>
        public static string Grid_Create {
            get {
                return ResourceManager.GetString("Grid_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Grid_Destroy {
            get {
                return ResourceManager.GetString("Grid_Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save changes 的本地化字符串。
        /// </summary>
        public static string Grid_SaveChanges {
            get {
                return ResourceManager.GetString("Grid_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Grid_Select {
            get {
                return ResourceManager.GetString("Grid_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort Ascending 的本地化字符串。
        /// </summary>
        public static string Grid_SortAscending {
            get {
                return ResourceManager.GetString("Grid_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort Descending 的本地化字符串。
        /// </summary>
        public static string Grid_SortDescending {
            get {
                return ResourceManager.GetString("Grid_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Grid_Update {
            get {
                return ResourceManager.GetString("Grid_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a column header and drop it here to group by that column 的本地化字符串。
        /// </summary>
        public static string Group_Empty {
            get {
                return ResourceManager.GetString("Group_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - {1} of {2} items 的本地化字符串。
        /// </summary>
        public static string Pager_Display {
            get {
                return ResourceManager.GetString("Pager_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No items to display 的本地化字符串。
        /// </summary>
        public static string Pager_Empty {
            get {
                return ResourceManager.GetString("Pager_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to the first page 的本地化字符串。
        /// </summary>
        public static string Pager_First {
            get {
                return ResourceManager.GetString("Pager_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 items per page 的本地化字符串。
        /// </summary>
        public static string Pager_ItemsPerPage {
            get {
                return ResourceManager.GetString("Pager_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to the last page 的本地化字符串。
        /// </summary>
        public static string Pager_Last {
            get {
                return ResourceManager.GetString("Pager_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to the next page 的本地化字符串。
        /// </summary>
        public static string Pager_Next {
            get {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of {0} 的本地化字符串。
        /// </summary>
        public static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page 的本地化字符串。
        /// </summary>
        public static string Pager_Page {
            get {
                return ResourceManager.GetString("Pager_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to the previous page 的本地化字符串。
        /// </summary>
        public static string Pager_Previous {
            get {
                return ResourceManager.GetString("Pager_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Pager_Refresh {
            get {
                return ResourceManager.GetString("Pager_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Upload_Cancel {
            get {
                return ResourceManager.GetString("Upload_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 drop files here to upload 的本地化字符串。
        /// </summary>
        public static string Upload_DropFilesHere {
            get {
                return ResourceManager.GetString("Upload_DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Upload_Remove {
            get {
                return ResourceManager.GetString("Upload_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry 的本地化字符串。
        /// </summary>
        public static string Upload_Retry {
            get {
                return ResourceManager.GetString("Upload_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select... 的本地化字符串。
        /// </summary>
        public static string Upload_Select {
            get {
                return ResourceManager.GetString("Upload_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 failed 的本地化字符串。
        /// </summary>
        public static string Upload_StatusFailed {
            get {
                return ResourceManager.GetString("Upload_StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 uploaded 的本地化字符串。
        /// </summary>
        public static string Upload_StatusUploaded {
            get {
                return ResourceManager.GetString("Upload_StatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 uploading 的本地化字符串。
        /// </summary>
        public static string Upload_StatusUploading {
            get {
                return ResourceManager.GetString("Upload_StatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload files 的本地化字符串。
        /// </summary>
        public static string Upload_UploadSelectedFiles {
            get {
                return ResourceManager.GetString("Upload_UploadSelectedFiles", resourceCulture);
            }
        }
    }
}
