//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kendo.Mvc.Resources
{
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Messages()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kendo.Mvc.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   查找类似 Background Color 的本地化字符串。
        /// </summary>
        public static string Editor_BackColor
        {
            get
            {
                return ResourceManager.GetString("Editor_BackColor", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Bold 的本地化字符串。
        /// </summary>
        public static string Editor_Bold
        {
            get
            {
                return ResourceManager.GetString("Editor_Bold", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Insert hyperlink 的本地化字符串。
        /// </summary>
        public static string Editor_CreateLink
        {
            get
            {
                return ResourceManager.GetString("Editor_CreateLink", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Are you sure you want to delete &quot;{0}&quot;? 的本地化字符串。
        /// </summary>
        public static string Editor_DeleteFile
        {
            get
            {
                return ResourceManager.GetString("Editor_DeleteFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 or 的本地化字符串。
        /// </summary>
        public static string Editor_DialogButtonSeparator
        {
            get
            {
                return ResourceManager.GetString("Editor_DialogButtonSeparator", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Editor_DialogCancel
        {
            get
            {
                return ResourceManager.GetString("Editor_DialogCancel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        public static string Editor_DialogInsert
        {
            get
            {
                return ResourceManager.GetString("Editor_DialogInsert", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A directory with this name was not found. 的本地化字符串。
        /// </summary>
        public static string Editor_DirectoryNotFound
        {
            get
            {
                return ResourceManager.GetString("Editor_DirectoryNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 drop files here to upload 的本地化字符串。
        /// </summary>
        public static string Editor_DropFilesHere
        {
            get
            {
                return ResourceManager.GetString("Editor_DropFilesHere", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Empty Folder 的本地化字符串。
        /// </summary>
        public static string Editor_EmptyFolder
        {
            get
            {
                return ResourceManager.GetString("Editor_EmptyFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Select font family 的本地化字符串。
        /// </summary>
        public static string Editor_FontName
        {
            get
            {
                return ResourceManager.GetString("Editor_FontName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 (inherited font) 的本地化字符串。
        /// </summary>
        public static string Editor_FontNameInherit
        {
            get
            {
                return ResourceManager.GetString("Editor_FontNameInherit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Select font size 的本地化字符串。
        /// </summary>
        public static string Editor_FontSize
        {
            get
            {
                return ResourceManager.GetString("Editor_FontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 (inherited size) 的本地化字符串。
        /// </summary>
        public static string Editor_FontSizeInherit
        {
            get
            {
                return ResourceManager.GetString("Editor_FontSizeInherit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        public static string Editor_ForeColor
        {
            get
            {
                return ResourceManager.GetString("Editor_ForeColor", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        public static string Editor_FormatBlock
        {
            get
            {
                return ResourceManager.GetString("Editor_FormatBlock", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Alternate text 的本地化字符串。
        /// </summary>
        public static string Editor_ImageAltText
        {
            get
            {
                return ResourceManager.GetString("Editor_ImageAltText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Web address 的本地化字符串。
        /// </summary>
        public static string Editor_ImageWebAddress
        {
            get
            {
                return ResourceManager.GetString("Editor_ImageWebAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indent 的本地化字符串。
        /// </summary>
        public static string Editor_Indent
        {
            get
            {
                return ResourceManager.GetString("Editor_Indent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Insert HTML 的本地化字符串。
        /// </summary>
        public static string Editor_InsertHtml
        {
            get
            {
                return ResourceManager.GetString("Editor_InsertHtml", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Insert image 的本地化字符串。
        /// </summary>
        public static string Editor_InsertImage
        {
            get
            {
                return ResourceManager.GetString("Editor_InsertImage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Insert ordered list 的本地化字符串。
        /// </summary>
        public static string Editor_InsertOrderedList
        {
            get
            {
                return ResourceManager.GetString("Editor_InsertOrderedList", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Insert unordered list 的本地化字符串。
        /// </summary>
        public static string Editor_InsertUnorderedList
        {
            get
            {
                return ResourceManager.GetString("Editor_InsertUnorderedList", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The selected file &quot;{0}&quot; is not valid. Supported file types are {1}. 的本地化字符串。
        /// </summary>
        public static string Editor_InvalidFileType
        {
            get
            {
                return ResourceManager.GetString("Editor_InvalidFileType", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Italic 的本地化字符串。
        /// </summary>
        public static string Editor_Italic
        {
            get
            {
                return ResourceManager.GetString("Editor_Italic", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Center text 的本地化字符串。
        /// </summary>
        public static string Editor_JustifyCenter
        {
            get
            {
                return ResourceManager.GetString("Editor_JustifyCenter", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Justify 的本地化字符串。
        /// </summary>
        public static string Editor_JustifyFull
        {
            get
            {
                return ResourceManager.GetString("Editor_JustifyFull", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Align text left 的本地化字符串。
        /// </summary>
        public static string Editor_JustifyLeft
        {
            get
            {
                return ResourceManager.GetString("Editor_JustifyLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Align text right 的本地化字符串。
        /// </summary>
        public static string Editor_JustifyRight
        {
            get
            {
                return ResourceManager.GetString("Editor_JustifyRight", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Open link in new window 的本地化字符串。
        /// </summary>
        public static string Editor_LinkOpenInNewWindow
        {
            get
            {
                return ResourceManager.GetString("Editor_LinkOpenInNewWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        public static string Editor_LinkText
        {
            get
            {
                return ResourceManager.GetString("Editor_LinkText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ToolTip 的本地化字符串。
        /// </summary>
        public static string Editor_LinkToolTip
        {
            get
            {
                return ResourceManager.GetString("Editor_LinkToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Web address 的本地化字符串。
        /// </summary>
        public static string Editor_LinkWebAddress
        {
            get
            {
                return ResourceManager.GetString("Editor_LinkWebAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Arrange by: 的本地化字符串。
        /// </summary>
        public static string Editor_OrderBy
        {
            get
            {
                return ResourceManager.GetString("Editor_OrderBy", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Editor_OrderByName
        {
            get
            {
                return ResourceManager.GetString("Editor_OrderByName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Editor_OrderBySize
        {
            get
            {
                return ResourceManager.GetString("Editor_OrderBySize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Outdent 的本地化字符串。
        /// </summary>
        public static string Editor_Outdent
        {
            get
            {
                return ResourceManager.GetString("Editor_Outdent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;A file with name &quot;{0}&quot; already exists in the current directory. Do you want to overwrite it? 的本地化字符串。
        /// </summary>
        public static string Editor_OverwriteFile
        {
            get
            {
                return ResourceManager.GetString("Editor_OverwriteFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Editor_Search
        {
            get
            {
                return ResourceManager.GetString("Editor_Search", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Strikethrough 的本地化字符串。
        /// </summary>
        public static string Editor_Strikethrough
        {
            get
            {
                return ResourceManager.GetString("Editor_Strikethrough", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Styles 的本地化字符串。
        /// </summary>
        public static string Editor_Styles
        {
            get
            {
                return ResourceManager.GetString("Editor_Styles", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Subscript 的本地化字符串。
        /// </summary>
        public static string Editor_Subscript
        {
            get
            {
                return ResourceManager.GetString("Editor_Subscript", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Superscript 的本地化字符串。
        /// </summary>
        public static string Editor_Superscript
        {
            get
            {
                return ResourceManager.GetString("Editor_Superscript", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Underline 的本地化字符串。
        /// </summary>
        public static string Editor_Underline
        {
            get
            {
                return ResourceManager.GetString("Editor_Underline", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Remove hyperlink 的本地化字符串。
        /// </summary>
        public static string Editor_Unlink
        {
            get
            {
                return ResourceManager.GetString("Editor_Unlink", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        public static string Editor_UploadFile
        {
            get
            {
                return ResourceManager.GetString("Editor_UploadFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        public static string Filter_And
        {
            get
            {
                return ResourceManager.GetString("Filter_And", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Filter_Clear
        {
            get
            {
                return ResourceManager.GetString("Filter_Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        public static string Filter_DateIsEqualTo
        {
            get
            {
                return ResourceManager.GetString("Filter_DateIsEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is after 的本地化字符串。
        /// </summary>
        public static string Filter_DateIsGreaterThan
        {
            get
            {
                return ResourceManager.GetString("Filter_DateIsGreaterThan", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is after or equal to 的本地化字符串。
        /// </summary>
        public static string Filter_DateIsGreaterThanOrEqualTo
        {
            get
            {
                return ResourceManager.GetString("Filter_DateIsGreaterThanOrEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is before 的本地化字符串。
        /// </summary>
        public static string Filter_DateIsLessThan
        {
            get
            {
                return ResourceManager.GetString("Filter_DateIsLessThan", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is before or equal to 的本地化字符串。
        /// </summary>
        public static string Filter_DateIsLessThanOrEqualTo
        {
            get
            {
                return ResourceManager.GetString("Filter_DateIsLessThanOrEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        public static string Filter_DateIsNotEqualTo
        {
            get
            {
                return ResourceManager.GetString("Filter_DateIsNotEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        public static string Filter_EnumIsEqualTo
        {
            get
            {
                return ResourceManager.GetString("Filter_EnumIsEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        public static string Filter_EnumIsNotEqualTo
        {
            get
            {
                return ResourceManager.GetString("Filter_EnumIsNotEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        public static string Filter_Filter
        {
            get
            {
                return ResourceManager.GetString("Filter_Filter", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Show items with value that: 的本地化字符串。
        /// </summary>
        public static string Filter_Info
        {
            get
            {
                return ResourceManager.GetString("Filter_Info", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 is false 的本地化字符串。
        /// </summary>
        public static string Filter_IsFalse
        {
            get
            {
                return ResourceManager.GetString("Filter_IsFalse", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 is true 的本地化字符串。
        /// </summary>
        public static string Filter_IsTrue
        {
            get
            {
                return ResourceManager.GetString("Filter_IsTrue", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        public static string Filter_NumberIsEqualTo
        {
            get
            {
                return ResourceManager.GetString("Filter_NumberIsEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is greater than 的本地化字符串。
        /// </summary>
        public static string Filter_NumberIsGreaterThan
        {
            get
            {
                return ResourceManager.GetString("Filter_NumberIsGreaterThan", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is greater than or equal to 的本地化字符串。
        /// </summary>
        public static string Filter_NumberIsGreaterThanOrEqualTo
        {
            get
            {
                return ResourceManager.GetString("Filter_NumberIsGreaterThanOrEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is less than 的本地化字符串。
        /// </summary>
        public static string Filter_NumberIsLessThan
        {
            get
            {
                return ResourceManager.GetString("Filter_NumberIsLessThan", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is less than or equal to 的本地化字符串。
        /// </summary>
        public static string Filter_NumberIsLessThanOrEqualTo
        {
            get
            {
                return ResourceManager.GetString("Filter_NumberIsLessThanOrEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        public static string Filter_NumberIsNotEqualTo
        {
            get
            {
                return ResourceManager.GetString("Filter_NumberIsNotEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Or 的本地化字符串。
        /// </summary>
        public static string Filter_Or
        {
            get
            {
                return ResourceManager.GetString("Filter_Or", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 -Select value- 的本地化字符串。
        /// </summary>
        public static string Filter_SelectValue
        {
            get
            {
                return ResourceManager.GetString("Filter_SelectValue", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Contains 的本地化字符串。
        /// </summary>
        public static string Filter_StringContains
        {
            get
            {
                return ResourceManager.GetString("Filter_StringContains", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Does not contain 的本地化字符串。
        /// </summary>
        public static string Filter_StringDoesNotContain
        {
            get
            {
                return ResourceManager.GetString("Filter_StringDoesNotContain", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Ends with 的本地化字符串。
        /// </summary>
        public static string Filter_StringEndsWith
        {
            get
            {
                return ResourceManager.GetString("Filter_StringEndsWith", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        public static string Filter_StringIsEqualTo
        {
            get
            {
                return ResourceManager.GetString("Filter_StringIsEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        public static string Filter_StringIsNotEqualTo
        {
            get
            {
                return ResourceManager.GetString("Filter_StringIsNotEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Starts with 的本地化字符串。
        /// </summary>
        public static string Filter_StringStartsWith
        {
            get
            {
                return ResourceManager.GetString("Filter_StringStartsWith", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Grid_Cancel
        {
            get
            {
                return ResourceManager.GetString("Grid_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cancel changes 的本地化字符串。
        /// </summary>
        public static string Grid_CancelChanges
        {
            get
            {
                return ResourceManager.GetString("Grid_CancelChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Columns 的本地化字符串。
        /// </summary>
        public static string Grid_Columns
        {
            get
            {
                return ResourceManager.GetString("Grid_Columns", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Are you sure you want to delete this item? 的本地化字符串。
        /// </summary>
        public static string Grid_Confirmation
        {
            get
            {
                return ResourceManager.GetString("Grid_Confirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Add new item 的本地化字符串。
        /// </summary>
        public static string Grid_Create
        {
            get
            {
                return ResourceManager.GetString("Grid_Create", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Grid_Destroy
        {
            get
            {
                return ResourceManager.GetString("Grid_Destroy", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Grid_Edit
        {
            get
            {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Save changes 的本地化字符串。
        /// </summary>
        public static string Grid_SaveChanges
        {
            get
            {
                return ResourceManager.GetString("Grid_SaveChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Grid_Select
        {
            get
            {
                return ResourceManager.GetString("Grid_Select", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Sort Ascending 的本地化字符串。
        /// </summary>
        public static string Grid_SortAscending
        {
            get
            {
                return ResourceManager.GetString("Grid_SortAscending", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Sort Descending 的本地化字符串。
        /// </summary>
        public static string Grid_SortDescending
        {
            get
            {
                return ResourceManager.GetString("Grid_SortDescending", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Grid_Update
        {
            get
            {
                return ResourceManager.GetString("Grid_Update", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Drag a column header and drop it here to group by that column 的本地化字符串。
        /// </summary>
        public static string Group_Empty
        {
            get
            {
                return ResourceManager.GetString("Group_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} - {1} of {2} items 的本地化字符串。
        /// </summary>
        public static string Pager_Display
        {
            get
            {
                return ResourceManager.GetString("Pager_Display", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 No items to display 的本地化字符串。
        /// </summary>
        public static string Pager_Empty
        {
            get
            {
                return ResourceManager.GetString("Pager_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Go to the first page 的本地化字符串。
        /// </summary>
        public static string Pager_First
        {
            get
            {
                return ResourceManager.GetString("Pager_First", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 items per page 的本地化字符串。
        /// </summary>
        public static string Pager_ItemsPerPage
        {
            get
            {
                return ResourceManager.GetString("Pager_ItemsPerPage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Go to the last page 的本地化字符串。
        /// </summary>
        public static string Pager_Last
        {
            get
            {
                return ResourceManager.GetString("Pager_Last", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Go to the next page 的本地化字符串。
        /// </summary>
        public static string Pager_Next
        {
            get
            {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 of {0} 的本地化字符串。
        /// </summary>
        public static string Pager_Of
        {
            get
            {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Page 的本地化字符串。
        /// </summary>
        public static string Pager_Page
        {
            get
            {
                return ResourceManager.GetString("Pager_Page", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Go to the previous page 的本地化字符串。
        /// </summary>
        public static string Pager_Previous
        {
            get
            {
                return ResourceManager.GetString("Pager_Previous", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Pager_Refresh
        {
            get
            {
                return ResourceManager.GetString("Pager_Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Upload_Cancel
        {
            get
            {
                return ResourceManager.GetString("Upload_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 drop files here to upload 的本地化字符串。
        /// </summary>
        public static string Upload_DropFilesHere
        {
            get
            {
                return ResourceManager.GetString("Upload_DropFilesHere", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Upload_Remove
        {
            get
            {
                return ResourceManager.GetString("Upload_Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Retry 的本地化字符串。
        /// </summary>
        public static string Upload_Retry
        {
            get
            {
                return ResourceManager.GetString("Upload_Retry", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Select... 的本地化字符串。
        /// </summary>
        public static string Upload_Select
        {
            get
            {
                return ResourceManager.GetString("Upload_Select", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 failed 的本地化字符串。
        /// </summary>
        public static string Upload_StatusFailed
        {
            get
            {
                return ResourceManager.GetString("Upload_StatusFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 uploaded 的本地化字符串。
        /// </summary>
        public static string Upload_StatusUploaded
        {
            get
            {
                return ResourceManager.GetString("Upload_StatusUploaded", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 uploading 的本地化字符串。
        /// </summary>
        public static string Upload_StatusUploading
        {
            get
            {
                return ResourceManager.GetString("Upload_StatusUploading", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Upload files 的本地化字符串。
        /// </summary>
        public static string Upload_UploadSelectedFiles
        {
            get
            {
                return ResourceManager.GetString("Upload_UploadSelectedFiles", resourceCulture);
            }
        }


        /// <summary>
        ///   查找类似 &quot;{0}&quot; array cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string ArrayCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("ArrayCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You must use InCell edit mode for batch updates. 的本地化字符串。
        /// </summary>
        internal static string BatchUpdatesRequireInCellMode
        {
            get
            {
                return ResourceManager.GetString("BatchUpdatesRequireInCellMode", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The Update data binding setting is required for batch updates. Please specify the Update action or url in the DataBinding configuration. 的本地化字符串。
        /// </summary>
        internal static string BatchUpdatesRequireUpdate
        {
            get
            {
                return ResourceManager.GetString("BatchUpdatesRequireUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &quot;{0}&quot; cannot be negative. 的本地化字符串。
        /// </summary>
        internal static string CannotBeNegative
        {
            get
            {
                return ResourceManager.GetString("CannotBeNegative", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &quot;{0}&quot; cannot be negative or zero. 的本地化字符串。
        /// </summary>
        internal static string CannotBeNegativeOrZero
        {
            get
            {
                return ResourceManager.GetString("CannotBeNegativeOrZero", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &quot;{0}&quot; cannot be null. 的本地化字符串。
        /// </summary>
        internal static string CannotBeNull
        {
            get
            {
                return ResourceManager.GetString("CannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &quot;{0}&quot; cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string CannotBeNullOrEmpty
        {
            get
            {
                return ResourceManager.GetString("CannotBeNullOrEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cannot find a public property of primitive type to sort by. 的本地化字符串。
        /// </summary>
        internal static string CannotFindPropertyToSortBy
        {
            get
            {
                return ResourceManager.GetString("CannotFindPropertyToSortBy", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cannot have more one column in order when sort mode is set to single column. 的本地化字符串。
        /// </summary>
        internal static string CannotHaveMoreOneColumnInOrderWhenSortModeIsSetToSingleColumn
        {
            get
            {
                return ResourceManager.GetString("CannotHaveMoreOneColumnInOrderWhenSortModeIsSetToSingleColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cannot route to class named &apos;Controller&apos;. 的本地化字符串。
        /// </summary>
        internal static string CannotRouteToClassNamedController
        {
            get
            {
                return ResourceManager.GetString("CannotRouteToClassNamedController", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cannot set AutoBind if widget is populated during initialization 的本地化字符串。
        /// </summary>
        internal static string CannotSetAutoBindIfBoundDuringInitialization
        {
            get
            {
                return ResourceManager.GetString("CannotSetAutoBindIfBoundDuringInitialization", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cannot use Ajax and WebService binding at the same time. 的本地化字符串。
        /// </summary>
        internal static string CannotUseAjaxAndWebServiceAtTheSameTime
        {
            get
            {
                return ResourceManager.GetString("CannotUseAjaxAndWebServiceAtTheSameTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cannot use only server templates in Ajax or WebService binding mode. Please specify a client template as well. 的本地化字符串。
        /// </summary>
        internal static string CannotUseTemplatesInAjaxOrWebService
        {
            get
            {
                return ResourceManager.GetString("CannotUseTemplatesInAjaxOrWebService", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cannot use Virtual Scroll with Server binding. 的本地化字符串。
        /// </summary>
        internal static string CannotUseVirtualScrollWithServerBinding
        {
            get
            {
                return ResourceManager.GetString("CannotUseVirtualScrollWithServerBinding", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &quot;{0}&quot; collection cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string CollectionCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("CollectionCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.
        ///
        ///The request for &apos;{0}&apos; has found the following matching controllers:{1} 的本地化字符串。
        /// </summary>
        internal static string ControllerNameAmbiguousWithoutRouteUrl
        {
            get
            {
                return ResourceManager.GetString("ControllerNameAmbiguousWithoutRouteUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request (&apos;{1}&apos;) does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.
        ///
        ///The request for &apos;{0}&apos; has found the following matching controllers:{2} 的本地化字符串。
        /// </summary>
        internal static string ControllerNameAmbiguousWithRouteUrl
        {
            get
            {
                return ResourceManager.GetString("ControllerNameAmbiguousWithRouteUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Controller name must end with &apos;Controller&apos;. 的本地化字符串。
        /// </summary>
        internal static string ControllerNameMustEndWithController
        {
            get
            {
                return ResourceManager.GetString("ControllerNameMustEndWithController", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Custom command routes is available only for server binding. 的本地化字符串。
        /// </summary>
        internal static string CustomCommandRoutesWithAjaxBinding
        {
            get
            {
                return ResourceManager.GetString("CustomCommandRoutesWithAjaxBinding", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 There is no DataSource Model Id property specified. 的本地化字符串。
        /// </summary>
        internal static string DataKeysEmpty
        {
            get
            {
                return ResourceManager.GetString("DataKeysEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 DataTable InLine editing and custom EditorTemplate per column is not supported 的本地化字符串。
        /// </summary>
        internal static string DataTableInLineEditingWithCustomEditorTemplates
        {
            get
            {
                return ResourceManager.GetString("DataTableInLineEditingWithCustomEditorTemplates", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You must specify TemplateName when PopUp edit mode is enabled with DataTable binding 的本地化字符串。
        /// </summary>
        internal static string DataTablePopUpTemplate
        {
            get
            {
                return ResourceManager.GetString("DataTablePopUpTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The Delete data binding setting is required by the delete command. Please specify the Delete action or url in the DataBinding configuration. 的本地化字符串。
        /// </summary>
        internal static string DeleteCommandRequiresDelete
        {
            get
            {
                return ResourceManager.GetString("DeleteCommandRequiresDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The Update data binding setting is required by the edit command. Please specify the Update action or url in the DataBinding configuration. 的本地化字符串。
        /// </summary>
        internal static string EditCommandRequiresUpdate
        {
            get
            {
                return ResourceManager.GetString("EditCommandRequiresUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} should not be bigger then {1}. 的本地化字符串。
        /// </summary>
        internal static string FirstPropertyShouldNotBeBiggerThenSecondProperty
        {
            get
            {
                return ResourceManager.GetString("FirstPropertyShouldNotBeBiggerThenSecondProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Group with specified name already exists. 的本地化字符串。
        /// </summary>
        internal static string GroupWithSpecifiedNameAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("GroupWithSpecifiedNameAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Group with specified name &quot;{0}&quot; already exists. Please specify a different name. 的本地化字符串。
        /// </summary>
        internal static string GroupWithSpecifiedNameAlreadyExistsPleaseSpecifyADifferentName
        {
            get
            {
                return ResourceManager.GetString("GroupWithSpecifiedNameAlreadyExistsPleaseSpecifyADifferentName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Group with &quot;{0}&quot; does not exist in {1} SharedWebAssets. 的本地化字符串。
        /// </summary>
        internal static string GroupWithSpecifiedNameDoesNotExistInAssetTypeOfSharedWebAssets
        {
            get
            {
                return ResourceManager.GetString("GroupWithSpecifiedNameDoesNotExistInAssetTypeOfSharedWebAssets", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Group with specified name &quot;{0}&quot; does not exist. Please make sure you have specified a correct name. 的本地化字符串。
        /// </summary>
        internal static string GroupWithSpecifiedNameDoesNotExistPleaseMakeSureYouHaveSpecifiedACorrectName
        {
            get
            {
                return ResourceManager.GetString("GroupWithSpecifiedNameDoesNotExistPleaseMakeSureYouHaveSpecifiedACorrectName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 InCell editing mode is not supported in server binding mode 的本地化字符串。
        /// </summary>
        internal static string InCellModeNotSupportedInServerBinding
        {
            get
            {
                return ResourceManager.GetString("InCellModeNotSupportedInServerBinding", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 InCell editing mode is not supported when ClientRowTemplate is used 的本地化字符串。
        /// </summary>
        internal static string InCellModeNotSupportedWithRowTemplate
        {
            get
            {
                return ResourceManager.GetString("InCellModeNotSupportedWithRowTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Provided index is out of range. 的本地化字符串。
        /// </summary>
        internal static string IndexOutOfRange
        {
            get
            {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The Insert data binding setting is required by the insert command. Please specify the Insert action or url in the DataBinding configuration. 的本地化字符串。
        /// </summary>
        internal static string InsertCommandRequiresInsert
        {
            get
            {
                return ResourceManager.GetString("InsertCommandRequiresInsert", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Item with specified source already exists. 的本地化字符串。
        /// </summary>
        internal static string ItemWithSpecifiedSourceAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("ItemWithSpecifiedSourceAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Local group with name &quot;{0}&quot; already exists. 的本地化字符串。
        /// </summary>
        internal static string LocalGroupWithSpecifiedNameAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("LocalGroupWithSpecifiedNameAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The key with the following name &quot;{0}&quot; was not found. Please update all localization files. 的本地化字符串。
        /// </summary>
        internal static string LocalizationKeyNotFound
        {
            get
            {
                return ResourceManager.GetString("LocalizationKeyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Bound columns require a field or property access expression. 的本地化字符串。
        /// </summary>
        internal static string MemberExpressionRequired
        {
            get
            {
                return ResourceManager.GetString("MemberExpressionRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} should be less than {1}. 的本地化字符串。
        /// </summary>
        internal static string MinPropertyMustBeLessThenMaxProperty
        {
            get
            {
                return ResourceManager.GetString("MinPropertyMustBeLessThenMaxProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Name cannot be blank. 的本地化字符串。
        /// </summary>
        internal static string NameCannotBeBlank
        {
            get
            {
                return ResourceManager.GetString("NameCannotBeBlank", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Name cannot contain spaces. 的本地化字符串。
        /// </summary>
        internal static string NameCannotContainSpaces
        {
            get
            {
                return ResourceManager.GetString("NameCannotContainSpaces", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &quot;None&quot; is only used for internal purpose. 的本地化字符串。
        /// </summary>
        internal static string NoneIsOnlyUsedForInternalPurpose
        {
            get
            {
                return ResourceManager.GetString("NoneIsOnlyUsedForInternalPurpose", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Only one ScriptRegistrar is allowed in a single request. 的本地化字符串。
        /// </summary>
        internal static string OnlyOneScriptRegistrarIsAllowedInASingleRequest
        {
            get
            {
                return ResourceManager.GetString("OnlyOneScriptRegistrarIsAllowedInASingleRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Only one StyleSheetRegistrar is allowed in a single request. 的本地化字符串。
        /// </summary>
        internal static string OnlyOneStyleSheetRegistrarIsAllowedInASingleRequest
        {
            get
            {
                return ResourceManager.GetString("OnlyOneStyleSheetRegistrarIsAllowedInASingleRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Only property and field expressions are supported 的本地化字符串。
        /// </summary>
        internal static string OnlyPropertyAndFieldExpressionsAreSupported
        {
            get
            {
                return ResourceManager.GetString("OnlyPropertyAndFieldExpressionsAreSupported", resourceCulture);
            }
        }
 

        /// <summary>
        ///   查找类似 Paging must be enabled to use PageOnScroll. 的本地化字符串。
        /// </summary>
        internal static string PagingMustBeEnabledToUsePageOnScroll
        {
            get
            {
                return ResourceManager.GetString("PagingMustBeEnabledToUsePageOnScroll", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The {0} must be bigger then 0. 的本地化字符串。
        /// </summary>
        internal static string PropertyMustBeBiggerThenZero
        {
            get
            {
                return ResourceManager.GetString("PropertyMustBeBiggerThenZero", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} must be positive number. 的本地化字符串。
        /// </summary>
        internal static string PropertyMustBePositiveNumber
        {
            get
            {
                return ResourceManager.GetString("PropertyMustBePositiveNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} should be bigger than {1} and less then {2} 的本地化字符串。
        /// </summary>
        internal static string PropertyShouldBeInRange
        {
            get
            {
                return ResourceManager.GetString("PropertyShouldBeInRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &quot;{0}&quot; class is no longer supported. To enable RTL support you must include telerik.rtl.css and apply the &quot;t-rtl&quot; class to a parent HTML element or the &lt;body&gt;. 的本地化字符串。
        /// </summary>
        internal static string Rtl
        {
            get
            {
                return ResourceManager.GetString("Rtl", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Scrolling must be enabled to use PageOnScroll. 的本地化字符串。
        /// </summary>
        internal static string ScrollingMustBeEnabledToUsePageOnScroll
        {
            get
            {
                return ResourceManager.GetString("ScrollingMustBeEnabledToUsePageOnScroll", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You must have SiteMap defined with key &quot;{0}&quot; in ViewData dictionary. 的本地化字符串。
        /// </summary>
        internal static string SiteMapShouldBeDefinedInViewData
        {
            get
            {
                return ResourceManager.GetString("SiteMapShouldBeDefinedInViewData", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Source must be a virtual path which should starts with &quot;~/&quot; 的本地化字符串。
        /// </summary>
        internal static string SourceMustBeAVirtualPathWhichShouldStartsWithTileAndSlash
        {
            get
            {
                return ResourceManager.GetString("SourceMustBeAVirtualPathWhichShouldStartsWithTileAndSlash", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Specified file does not exist: &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string SpecifiedFileDoesNotExist
        {
            get
            {
                return ResourceManager.GetString("SpecifiedFileDoesNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Passed string cannot be parsed to DateTime object. 的本地化字符串。
        /// </summary>
        internal static string StringNotCorrectDate
        {
            get
            {
                return ResourceManager.GetString("StringNotCorrectDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Passed string cannot be parsed to TimeSpan object. 的本地化字符串。
        /// </summary>
        internal static string StringNotCorrectTimeSpan
        {
            get
            {
                return ResourceManager.GetString("StringNotCorrectTimeSpan", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified method is not an action method. 的本地化字符串。
        /// </summary>
        internal static string TheSpecifiedMethodIsNotAnActionMethod
        {
            get
            {
                return ResourceManager.GetString("TheSpecifiedMethodIsNotAnActionMethod", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Time should be bigger than MinTime and less than MaxTime. 的本地化字符串。
        /// </summary>
        internal static string TimeOutOfRange
        {
            get
            {
                return ResourceManager.GetString("TimeOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You should set Tooltip container. Tooltip.For(container) 的本地化字符串。
        /// </summary>
        internal static string TooltipContainerShouldBeSet
        {
            get
            {
                return ResourceManager.GetString("TooltipContainerShouldBeSet", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You cannot set Url and ContentUrl at the same time. 的本地化字符串。
        /// </summary>
        internal static string UrlAndContentUrlCannotBeSet
        {
            get
            {
                return ResourceManager.GetString("UrlAndContentUrlCannotBeSet", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is invalid. 的本地化字符串。
        /// </summary>
        internal static string ValueNotValidForProperty
        {
            get
            {
                return ResourceManager.GetString("ValueNotValidForProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The Url of the WebService must be set 的本地化字符串。
        /// </summary>
        internal static string WebServiceUrlRequired
        {
            get
            {
                return ResourceManager.GetString("WebServiceUrlRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You cannot add more than once column when sort mode is set to single column. 的本地化字符串。
        /// </summary>
        internal static string YouCannotAddMoreThanOnceColumnWhenSortModeIsSetToSingle
        {
            get
            {
                return ResourceManager.GetString("YouCannotAddMoreThanOnceColumnWhenSortModeIsSetToSingle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You cannot use non generic BindTo overload without EnableCustomBinding set to true 的本地化字符串。
        /// </summary>
        internal static string YouCannotCallBindToWithoutCustomBinding
        {
            get
            {
                return ResourceManager.GetString("YouCannotCallBindToWithoutCustomBinding", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You cannot call render more than once. 的本地化字符串。
        /// </summary>
        internal static string YouCannotCallRenderMoreThanOnce
        {
            get
            {
                return ResourceManager.GetString("YouCannotCallRenderMoreThanOnce", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You cannot call Start more than once. 的本地化字符串。
        /// </summary>
        internal static string YouCannotCallStartMoreThanOnce
        {
            get
            {
                return ResourceManager.GetString("YouCannotCallStartMoreThanOnce", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You cannot configure a shared web asset group. 的本地化字符串。
        /// </summary>
        internal static string YouCannotConfigureASharedWebAssetGroup
        {
            get
            {
                return ResourceManager.GetString("YouCannotConfigureASharedWebAssetGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 You must have to call Start prior calling this method. 的本地化字符串。
        /// </summary>
        internal static string YouMustHaveToCallStartPriorCallingThisMethod
        {
            get
            {
                return ResourceManager.GetString("YouMustHaveToCallStartPriorCallingThisMethod", resourceCulture);
            }
        }
    }
}
